// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace EllisWinAppTest
{
    using System.CodeDom.Compiler;
    using System.Drawing;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;


    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Data will be entered in 2 rows of the schedule table
        /// </summary>
        public void EnterDatainJobOrderSchedule()
        {
            #region Variable Declarations
            WinComboBox uIItemComboBox = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UIItemComboBox;
            WinCell uIItem1250Cell = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UIItem1250Cell;
            WinClient uIDesktopClient = this.UIItemWindow.UIItemWindow1.UIDesktopClient;
            WinCell uITrueCell = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UITrueCell;
            WinCheckBox uIItemCheckBox = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UIItemCheckBox;
            WinCell uIItem0Cell = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UIItem0Cell;
            WinCell uIItem0Cell1 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UIItem0Cell1;
            WinCell uIItem0Cell2 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UIItem0Cell2;
            WinEdit uI_grdJobOrderScheduleEdit = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UI_grdJobOrderScheduleEdit;
            WinCell uINOTECell = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UINOTECell;
            WinEdit uIItemEdit = this.UIEstimatedHoursWindow.UIItemWindow.UIItemEdit;
            WinEdit uI_mskEstimatedHrsEdit1 = this.UIEstimatedHoursWindow.UI_mskEstimatedHrsWindow.UI_mskEstimatedHrsEdit.UI_mskEstimatedHrsEdit1;
            WinEdit uI_mskEstimatedHrsEdit11 = this.UIEstimatedHoursWindow.UI_mskEstimatedHrsWindow.UI_mskEstimatedHrsEdit1;
            WinButton uIOKButton = this.UIEstimatedHoursWindow.UIOKWindow.UIOKButton;
            WinCell uIItem0Cell3 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UIItem0Cell3;
            WinEdit uI_grdJobOrderScheduleEdit1 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UI_grdJobOrderScheduleEdit1;
            WinCell uIItem0Cell4 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UIItem0Cell4;
            WinEdit uI_grdJobOrderScheduleEdit2 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UI_grdJobOrderScheduleEdit2;
            WinCell uIItem0Cell5 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UIItem0Cell5;
            WinEdit uI_grdJobOrderScheduleEdit3 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UI_grdJobOrderScheduleEdit3;
            WinCell uIItem0Cell6 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UIItem0Cell6;
            WinEdit uI_grdJobOrderScheduleEdit4 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UI_grdJobOrderScheduleEdit4;
            WinCell uIItemCell = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow.UIItemCell;
            WinCell uIItem1200AMCell = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UI_grdJobOrderScheduleTable.UITemplateAddRowRow.UIItem1200AMCell;
            WinComboBox uIItemComboBox1 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UIItemComboBox;
            WinComboBox uIItemComboBox11 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UIItemComboBox1;
            WinCell uITrueCell1 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UITrueCell;
            WinCheckBox uIItemCheckBox1 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UIItemCheckBox;
            WinCell uIItem0Cell7 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UIItem0Cell;
            WinEdit uI_grdJobOrderScheduleEdit5 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UI_grdJobOrderScheduleEdit;
            WinCell uIItem0Cell11 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UIItem0Cell1;
            WinEdit uI_grdJobOrderScheduleEdit11 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UI_grdJobOrderScheduleEdit1;
            WinCell uIItem0Cell21 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UIItem0Cell2;
            WinEdit uI_grdJobOrderScheduleEdit21 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UI_grdJobOrderScheduleEdit2;
            WinCell uIItem0Cell31 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UIItem0Cell3;
            WinEdit uI_grdJobOrderScheduleEdit31 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UI_grdJobOrderScheduleEdit3;
            WinCell uIItem0Cell41 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UIItem0Cell4;
            WinEdit uI_grdJobOrderScheduleEdit41 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UI_grdJobOrderScheduleEdit4;
            WinCell uIItemCell1 = this.UIItem000991331JobOrdeWindow.UI_grdJobOrderScheduleWindow.UIAddRowRow1.UIItemCell;
            #endregion

            // Select '08:30 pm' in combo box
            uIItemComboBox.SelectedItem = this.EnterDatainJobOrderScheduleParams.UIItemComboBoxSelectedItem;

            // Click '1250' cell
            Mouse.Click(uIItem1250Cell, new Point(25, 9));

            // Click 'Desktop' client
            Mouse.Click(uIDesktopClient, new Point(22, 36));

            // Click 'True' cell
            Mouse.Click(uITrueCell, new Point(30, 9));

            // Click check box
            Mouse.Click(uIItemCheckBox, new Point(29, 8));

            // Click '0' cell
            Mouse.Click(uIItem0Cell, new Point(18, 8));

            // Click '0' cell
            Mouse.Click(uIItem0Cell1, new Point(12, 11));

            // Click '0' cell
            Mouse.Click(uIItem0Cell2, new Point(19, 7));

            // Type '________08' in '_grdJobOrderSchedule' text box
            uI_grdJobOrderScheduleEdit.Text = this.EnterDatainJobOrderScheduleParams.UI_grdJobOrderScheduleEditText;

            // Click 'NOTE' cell
            Mouse.Click(uINOTECell, new Point(7, 10));

            // Type 'Dispatch for Monday' in text box
            uIItemEdit.Text = this.EnterDatainJobOrderScheduleParams.UIItemEditText;

            // Click '_mskEstimatedHrs' text box
            Mouse.Click(uI_mskEstimatedHrsEdit1, new Point(0, 8));

            // Type '{Delete}{NumPad8}' in '_mskEstimatedHrs' text box
            Keyboard.SendKeys(uI_mskEstimatedHrsEdit11, this.EnterDatainJobOrderScheduleParams.UI_mskEstimatedHrsEdit1SendKeys, ModifierKeys.None);

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(28, 15));

            // Click '0' cell
            Mouse.Click(uIItem0Cell1, new Point(26, 11));

            // Click '0' cell
            Mouse.Click(uIItem0Cell3, new Point(17, 7));

            // Type '_______016' in '_grdJobOrderSchedule' text box
            uI_grdJobOrderScheduleEdit1.Text = this.EnterDatainJobOrderScheduleParams.UI_grdJobOrderScheduleEdit1Text;

            // Click '0' cell
            Mouse.Click(uIItem0Cell4, new Point(14, 7));

            // Type '_______016' in '_grdJobOrderSchedule' text box
            uI_grdJobOrderScheduleEdit2.Text = this.EnterDatainJobOrderScheduleParams.UI_grdJobOrderScheduleEdit2Text;

            // Click '0' cell
            Mouse.Click(uIItem0Cell5, new Point(17, 9));

            // Type '_______016' in '_grdJobOrderSchedule' text box
            uI_grdJobOrderScheduleEdit3.Text = this.EnterDatainJobOrderScheduleParams.UI_grdJobOrderScheduleEdit3Text;

            // Click '0' cell
            Mouse.Click(uIItem0Cell6, new Point(16, 10));

            // Type '_______016' in '_grdJobOrderSchedule' text box
            uI_grdJobOrderScheduleEdit4.Text = this.EnterDatainJobOrderScheduleParams.UI_grdJobOrderScheduleEdit4Text;

            // Click '>>>>' cell
            Mouse.Click(uIItemCell, new Point(13, 11));

            // Click '12:00 AM' cell
            Mouse.Click(uIItem1200AMCell, new Point(37, 9));

            // Select '10:30 am' in combo box
            uIItemComboBox1.SelectedItem = this.EnterDatainJobOrderScheduleParams.UIItemComboBoxSelectedItem1;

            // Type '{Tab}' in combo box
            Keyboard.SendKeys(uIItemComboBox1, this.EnterDatainJobOrderScheduleParams.UIItemComboBoxSendKeys, ModifierKeys.None);

            // Click combo box
            Mouse.Click(uIItemComboBox11, new Point(22, 8));

            // Click 'Desktop' client
            Mouse.Click(uIDesktopClient, new Point(17, 90));

            // Click 'True' cell
            Mouse.Click(uITrueCell1, new Point(28, 8));

            // Click check box
            Mouse.Click(uIItemCheckBox1, new Point(27, 7));

            // Click '0' cell
            Mouse.Click(uIItem0Cell7, new Point(10, 10));

            // Type '________04' in '_grdJobOrderSchedule' text box
            uI_grdJobOrderScheduleEdit5.Text = this.EnterDatainJobOrderScheduleParams.UI_grdJobOrderScheduleEditText1;

            // Type '{Tab}' in '_grdJobOrderSchedule' text box
            Keyboard.SendKeys(uI_grdJobOrderScheduleEdit5, this.EnterDatainJobOrderScheduleParams.UI_grdJobOrderScheduleEditSendKeys, ModifierKeys.None);

            // Click '0' cell
            Mouse.Click(uIItem0Cell11, new Point(21, 10));

            // Type '________08' in '_grdJobOrderSchedule' text box
            uI_grdJobOrderScheduleEdit11.Text = this.EnterDatainJobOrderScheduleParams.UI_grdJobOrderScheduleEdit1Text1;

            // Click '0' cell
            Mouse.Click(uIItem0Cell21, new Point(20, 6));

            // Type '________08' in '_grdJobOrderSchedule' text box
            uI_grdJobOrderScheduleEdit21.Text = this.EnterDatainJobOrderScheduleParams.UI_grdJobOrderScheduleEdit2Text1;

            // Click '0' cell
            Mouse.Click(uIItem0Cell31, new Point(25, 5));

            // Type '________08' in '_grdJobOrderSchedule' text box
            uI_grdJobOrderScheduleEdit31.Text = this.EnterDatainJobOrderScheduleParams.UI_grdJobOrderScheduleEdit3Text1;

            // Click '0' cell
            Mouse.Click(uIItem0Cell41, new Point(22, 12));

            // Type '________08' in '_grdJobOrderSchedule' text box
            uI_grdJobOrderScheduleEdit41.Text = this.EnterDatainJobOrderScheduleParams.UI_grdJobOrderScheduleEdit4Text1;

            // Click '>>>>' cell
            Mouse.Click(uIItemCell1, new Point(33, 11));
        }
        
        #region Properties
        public virtual EnterDatainJobOrderScheduleParams EnterDatainJobOrderScheduleParams
        {
            get
            {
                if ((this.mEnterDatainJobOrderScheduleParams == null))
                {
                    this.mEnterDatainJobOrderScheduleParams = new EnterDatainJobOrderScheduleParams();
                }
                return this.mEnterDatainJobOrderScheduleParams;
            }
        }
        
        public UIItem000991331JobOrdeWindow UIItem000991331JobOrdeWindow
        {
            get
            {
                if ((this.mUIItem000991331JobOrdeWindow == null))
                {
                    this.mUIItem000991331JobOrdeWindow = new UIItem000991331JobOrdeWindow();
                }
                return this.mUIItem000991331JobOrdeWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIEstimatedHoursWindow UIEstimatedHoursWindow
        {
            get
            {
                if ((this.mUIEstimatedHoursWindow == null))
                {
                    this.mUIEstimatedHoursWindow = new UIEstimatedHoursWindow();
                }
                return this.mUIEstimatedHoursWindow;
            }
        }
        #endregion
        
        #region Fields
        private EnterDatainJobOrderScheduleParams mEnterDatainJobOrderScheduleParams;
        
        private UIItem000991331JobOrdeWindow mUIItem000991331JobOrdeWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIEstimatedHoursWindow mUIEstimatedHoursWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EnterDatainJobOrderSchedule'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class EnterDatainJobOrderScheduleParams
    {
        
        #region Fields
        /// <summary>
        /// Select '08:30 pm' in combo box
        /// </summary>
        public string UIItemComboBoxSelectedItem = "08:30 pm";
        
        /// <summary>
        /// Type '________08' in '_grdJobOrderSchedule' text box
        /// </summary>
        public string UI_grdJobOrderScheduleEditText = "________08";
        
        /// <summary>
        /// Type 'Dispatch for Monday' in text box
        /// </summary>
        public string UIItemEditText = "Dispatch for Monday";
        
        /// <summary>
        /// Type '{Delete}{NumPad8}' in '_mskEstimatedHrs' text box
        /// </summary>
        public string UI_mskEstimatedHrsEdit1SendKeys = "{Delete}{NumPad8}";
        
        /// <summary>
        /// Type '_______016' in '_grdJobOrderSchedule' text box
        /// </summary>
        public string UI_grdJobOrderScheduleEdit1Text = "_______016";
        
        /// <summary>
        /// Type '_______016' in '_grdJobOrderSchedule' text box
        /// </summary>
        public string UI_grdJobOrderScheduleEdit2Text = "_______016";
        
        /// <summary>
        /// Type '_______016' in '_grdJobOrderSchedule' text box
        /// </summary>
        public string UI_grdJobOrderScheduleEdit3Text = "_______016";
        
        /// <summary>
        /// Type '_______016' in '_grdJobOrderSchedule' text box
        /// </summary>
        public string UI_grdJobOrderScheduleEdit4Text = "_______016";
        
        /// <summary>
        /// Select '10:30 am' in combo box
        /// </summary>
        public string UIItemComboBoxSelectedItem1 = "10:30 am";
        
        /// <summary>
        /// Type '{Tab}' in combo box
        /// </summary>
        public string UIItemComboBoxSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '________04' in '_grdJobOrderSchedule' text box
        /// </summary>
        public string UI_grdJobOrderScheduleEditText1 = "________04";
        
        /// <summary>
        /// Type '{Tab}' in '_grdJobOrderSchedule' text box
        /// </summary>
        public string UI_grdJobOrderScheduleEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '________08' in '_grdJobOrderSchedule' text box
        /// </summary>
        public string UI_grdJobOrderScheduleEdit1Text1 = "________08";
        
        /// <summary>
        /// Type '________08' in '_grdJobOrderSchedule' text box
        /// </summary>
        public string UI_grdJobOrderScheduleEdit2Text1 = "________08";
        
        /// <summary>
        /// Type '________08' in '_grdJobOrderSchedule' text box
        /// </summary>
        public string UI_grdJobOrderScheduleEdit3Text1 = "________08";
        
        /// <summary>
        /// Type '________08' in '_grdJobOrderSchedule' text box
        /// </summary>
        public string UI_grdJobOrderScheduleEdit4Text1 = "________08";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItem000991331JobOrdeWindow : WinWindow
    {
        
        public UIItem000991331JobOrdeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "000991331-Job Order Profile";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("000991331-Job Order Profile");
            #endregion
        }
        
        #region Properties
        public UI_grdJobOrderScheduleWindow UI_grdJobOrderScheduleWindow
        {
            get
            {
                if ((this.mUI_grdJobOrderScheduleWindow == null))
                {
                    this.mUI_grdJobOrderScheduleWindow = new UI_grdJobOrderScheduleWindow(this);
                }
                return this.mUI_grdJobOrderScheduleWindow;
            }
        }
        #endregion
        
        #region Fields
        private UI_grdJobOrderScheduleWindow mUI_grdJobOrderScheduleWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UI_grdJobOrderScheduleWindow : WinWindow
    {
        
        public UI_grdJobOrderScheduleWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_grdJobOrderSchedule";
            this.WindowTitles.Add("000991331-Job Order Profile");
            #endregion
        }
        
        #region Properties
        public UIAddRowRow UIAddRowRow
        {
            get
            {
                if ((this.mUIAddRowRow == null))
                {
                    this.mUIAddRowRow = new UIAddRowRow(this);
                }
                return this.mUIAddRowRow;
            }
        }
        
        public UI_grdJobOrderScheduleTable UI_grdJobOrderScheduleTable
        {
            get
            {
                if ((this.mUI_grdJobOrderScheduleTable == null))
                {
                    this.mUI_grdJobOrderScheduleTable = new UI_grdJobOrderScheduleTable(this);
                }
                return this.mUI_grdJobOrderScheduleTable;
            }
        }
        
        public UIAddRowRow1 UIAddRowRow1
        {
            get
            {
                if ((this.mUIAddRowRow1 == null))
                {
                    this.mUIAddRowRow1 = new UIAddRowRow1(this);
                }
                return this.mUIAddRowRow1;
            }
        }
        #endregion
        
        #region Fields
        private UIAddRowRow mUIAddRowRow;
        
        private UI_grdJobOrderScheduleTable mUI_grdJobOrderScheduleTable;
        
        private UIAddRowRow1 mUIAddRowRow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAddRowRow : WinRow
    {
        
        public UIAddRowRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Name] = "Add Row";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("000991331-Job Order Profile");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIItemComboBox.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        
        public WinCell UIItem1250Cell
        {
            get
            {
                if ((this.mUIItem1250Cell == null))
                {
                    this.mUIItem1250Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem1250Cell.SearchProperties[WinCell.PropertyNames.Value] = "1250";
                    this.mUIItem1250Cell.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem1250Cell;
            }
        }
        
        public WinCell UITrueCell
        {
            get
            {
                if ((this.mUITrueCell == null))
                {
                    this.mUITrueCell = new WinCell(this);
                    #region Search Criteria
                    this.mUITrueCell.SearchProperties[WinCell.PropertyNames.Value] = "True";
                    this.mUITrueCell.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUITrueCell;
            }
        }
        
        public WinCheckBox UIItemCheckBox
        {
            get
            {
                if ((this.mUIItemCheckBox == null))
                {
                    this.mUIItemCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIItemCheckBox.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItemCheckBox;
            }
        }
        
        public WinCell UIItem0Cell
        {
            get
            {
                if ((this.mUIItem0Cell == null))
                {
                    this.mUIItem0Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem0Cell;
            }
        }
        
        public WinCell UIItem0Cell1
        {
            get
            {
                if ((this.mUIItem0Cell1 == null))
                {
                    this.mUIItem0Cell1 = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell1.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell1.SearchProperties[WinCell.PropertyNames.Instance] = "2";
                    this.mUIItem0Cell1.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem0Cell1;
            }
        }
        
        public WinCell UIItem0Cell2
        {
            get
            {
                if ((this.mUIItem0Cell2 == null))
                {
                    this.mUIItem0Cell2 = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell2.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell2.SearchProperties[WinCell.PropertyNames.Instance] = "3";
                    this.mUIItem0Cell2.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem0Cell2;
            }
        }
        
        public WinEdit UI_grdJobOrderScheduleEdit
        {
            get
            {
                if ((this.mUI_grdJobOrderScheduleEdit == null))
                {
                    this.mUI_grdJobOrderScheduleEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_grdJobOrderScheduleEdit.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUI_grdJobOrderScheduleEdit;
            }
        }
        
        public WinCell UINOTECell
        {
            get
            {
                if ((this.mUINOTECell == null))
                {
                    this.mUINOTECell = new WinCell(this);
                    #region Search Criteria
                    this.mUINOTECell.SearchProperties[WinCell.PropertyNames.Name] = "NOTE";
                    this.mUINOTECell.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUINOTECell;
            }
        }
        
        public WinCell UIItem0Cell3
        {
            get
            {
                if ((this.mUIItem0Cell3 == null))
                {
                    this.mUIItem0Cell3 = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell3.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell3.SearchProperties[WinCell.PropertyNames.Instance] = "3";
                    this.mUIItem0Cell3.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem0Cell3;
            }
        }
        
        public WinEdit UI_grdJobOrderScheduleEdit1
        {
            get
            {
                if ((this.mUI_grdJobOrderScheduleEdit1 == null))
                {
                    this.mUI_grdJobOrderScheduleEdit1 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_grdJobOrderScheduleEdit1.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUI_grdJobOrderScheduleEdit1;
            }
        }
        
        public WinCell UIItem0Cell4
        {
            get
            {
                if ((this.mUIItem0Cell4 == null))
                {
                    this.mUIItem0Cell4 = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell4.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell4.SearchProperties[WinCell.PropertyNames.Instance] = "3";
                    this.mUIItem0Cell4.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem0Cell4;
            }
        }
        
        public WinEdit UI_grdJobOrderScheduleEdit2
        {
            get
            {
                if ((this.mUI_grdJobOrderScheduleEdit2 == null))
                {
                    this.mUI_grdJobOrderScheduleEdit2 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_grdJobOrderScheduleEdit2.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUI_grdJobOrderScheduleEdit2;
            }
        }
        
        public WinCell UIItem0Cell5
        {
            get
            {
                if ((this.mUIItem0Cell5 == null))
                {
                    this.mUIItem0Cell5 = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell5.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell5.SearchProperties[WinCell.PropertyNames.Instance] = "3";
                    this.mUIItem0Cell5.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem0Cell5;
            }
        }
        
        public WinEdit UI_grdJobOrderScheduleEdit3
        {
            get
            {
                if ((this.mUI_grdJobOrderScheduleEdit3 == null))
                {
                    this.mUI_grdJobOrderScheduleEdit3 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_grdJobOrderScheduleEdit3.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUI_grdJobOrderScheduleEdit3;
            }
        }
        
        public WinCell UIItem0Cell6
        {
            get
            {
                if ((this.mUIItem0Cell6 == null))
                {
                    this.mUIItem0Cell6 = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell6.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell6.SearchProperties[WinCell.PropertyNames.Instance] = "3";
                    this.mUIItem0Cell6.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem0Cell6;
            }
        }
        
        public WinEdit UI_grdJobOrderScheduleEdit4
        {
            get
            {
                if ((this.mUI_grdJobOrderScheduleEdit4 == null))
                {
                    this.mUI_grdJobOrderScheduleEdit4 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_grdJobOrderScheduleEdit4.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUI_grdJobOrderScheduleEdit4;
            }
        }
        
        public WinCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItemCell.SearchProperties[WinCell.PropertyNames.Value] = "    >>>>";
                    this.mUIItemCell.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItemCell;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIItemComboBox;
        
        private WinCell mUIItem1250Cell;
        
        private WinCell mUITrueCell;
        
        private WinCheckBox mUIItemCheckBox;
        
        private WinCell mUIItem0Cell;
        
        private WinCell mUIItem0Cell1;
        
        private WinCell mUIItem0Cell2;
        
        private WinEdit mUI_grdJobOrderScheduleEdit;
        
        private WinCell mUINOTECell;
        
        private WinCell mUIItem0Cell3;
        
        private WinEdit mUI_grdJobOrderScheduleEdit1;
        
        private WinCell mUIItem0Cell4;
        
        private WinEdit mUI_grdJobOrderScheduleEdit2;
        
        private WinCell mUIItem0Cell5;
        
        private WinEdit mUI_grdJobOrderScheduleEdit3;
        
        private WinCell mUIItem0Cell6;
        
        private WinEdit mUI_grdJobOrderScheduleEdit4;
        
        private WinCell mUIItemCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UI_grdJobOrderScheduleTable : WinTable
    {
        
        public UI_grdJobOrderScheduleTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("000991331-Job Order Profile");
            #endregion
        }
        
        #region Properties
        public UITemplateAddRowRow UITemplateAddRowRow
        {
            get
            {
                if ((this.mUITemplateAddRowRow == null))
                {
                    this.mUITemplateAddRowRow = new UITemplateAddRowRow(this);
                }
                return this.mUITemplateAddRowRow;
            }
        }
        #endregion
        
        #region Fields
        private UITemplateAddRowRow mUITemplateAddRowRow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITemplateAddRowRow : WinRow
    {
        
        public UITemplateAddRowRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Name] = "Template Add Row";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("000991331-Job Order Profile");
            #endregion
        }
        
        #region Properties
        public WinCell UIItem1200AMCell
        {
            get
            {
                if ((this.mUIItem1200AMCell == null))
                {
                    this.mUIItem1200AMCell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem1200AMCell.SearchProperties[WinCell.PropertyNames.Value] = "12:00 AM";
                    this.mUIItem1200AMCell.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem1200AMCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIItem1200AMCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAddRowRow1 : WinRow
    {
        
        public UIAddRowRow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Name] = "Add Row";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("000991331-Job Order Profile");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIItemComboBox.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        
        public WinComboBox UIItemComboBox1
        {
            get
            {
                if ((this.mUIItemComboBox1 == null))
                {
                    this.mUIItemComboBox1 = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIItemComboBox1.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItemComboBox1;
            }
        }
        
        public WinCell UITrueCell
        {
            get
            {
                if ((this.mUITrueCell == null))
                {
                    this.mUITrueCell = new WinCell(this);
                    #region Search Criteria
                    this.mUITrueCell.SearchProperties[WinCell.PropertyNames.Value] = "True";
                    this.mUITrueCell.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUITrueCell;
            }
        }
        
        public WinCheckBox UIItemCheckBox
        {
            get
            {
                if ((this.mUIItemCheckBox == null))
                {
                    this.mUIItemCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIItemCheckBox.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItemCheckBox;
            }
        }
        
        public WinCell UIItem0Cell
        {
            get
            {
                if ((this.mUIItem0Cell == null))
                {
                    this.mUIItem0Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell.SearchProperties[WinCell.PropertyNames.Instance] = "3";
                    this.mUIItem0Cell.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem0Cell;
            }
        }
        
        public WinEdit UI_grdJobOrderScheduleEdit
        {
            get
            {
                if ((this.mUI_grdJobOrderScheduleEdit == null))
                {
                    this.mUI_grdJobOrderScheduleEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_grdJobOrderScheduleEdit.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUI_grdJobOrderScheduleEdit;
            }
        }
        
        public WinCell UIItem0Cell1
        {
            get
            {
                if ((this.mUIItem0Cell1 == null))
                {
                    this.mUIItem0Cell1 = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell1.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell1.SearchProperties[WinCell.PropertyNames.Instance] = "3";
                    this.mUIItem0Cell1.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem0Cell1;
            }
        }
        
        public WinEdit UI_grdJobOrderScheduleEdit1
        {
            get
            {
                if ((this.mUI_grdJobOrderScheduleEdit1 == null))
                {
                    this.mUI_grdJobOrderScheduleEdit1 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_grdJobOrderScheduleEdit1.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUI_grdJobOrderScheduleEdit1;
            }
        }
        
        public WinCell UIItem0Cell2
        {
            get
            {
                if ((this.mUIItem0Cell2 == null))
                {
                    this.mUIItem0Cell2 = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell2.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell2.SearchProperties[WinCell.PropertyNames.Instance] = "3";
                    this.mUIItem0Cell2.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem0Cell2;
            }
        }
        
        public WinEdit UI_grdJobOrderScheduleEdit2
        {
            get
            {
                if ((this.mUI_grdJobOrderScheduleEdit2 == null))
                {
                    this.mUI_grdJobOrderScheduleEdit2 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_grdJobOrderScheduleEdit2.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUI_grdJobOrderScheduleEdit2;
            }
        }
        
        public WinCell UIItem0Cell3
        {
            get
            {
                if ((this.mUIItem0Cell3 == null))
                {
                    this.mUIItem0Cell3 = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell3.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell3.SearchProperties[WinCell.PropertyNames.Instance] = "3";
                    this.mUIItem0Cell3.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem0Cell3;
            }
        }
        
        public WinEdit UI_grdJobOrderScheduleEdit3
        {
            get
            {
                if ((this.mUI_grdJobOrderScheduleEdit3 == null))
                {
                    this.mUI_grdJobOrderScheduleEdit3 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_grdJobOrderScheduleEdit3.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUI_grdJobOrderScheduleEdit3;
            }
        }
        
        public WinCell UIItem0Cell4
        {
            get
            {
                if ((this.mUIItem0Cell4 == null))
                {
                    this.mUIItem0Cell4 = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem0Cell4.SearchProperties[WinCell.PropertyNames.Value] = "0";
                    this.mUIItem0Cell4.SearchProperties[WinCell.PropertyNames.Instance] = "3";
                    this.mUIItem0Cell4.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItem0Cell4;
            }
        }
        
        public WinEdit UI_grdJobOrderScheduleEdit4
        {
            get
            {
                if ((this.mUI_grdJobOrderScheduleEdit4 == null))
                {
                    this.mUI_grdJobOrderScheduleEdit4 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_grdJobOrderScheduleEdit4.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUI_grdJobOrderScheduleEdit4;
            }
        }
        
        public WinCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItemCell.SearchProperties[WinCell.PropertyNames.Value] = "    >>>>";
                    this.mUIItemCell.WindowTitles.Add("000991331-Job Order Profile");
                    #endregion
                }
                return this.mUIItemCell;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIItemComboBox;
        
        private WinComboBox mUIItemComboBox1;
        
        private WinCell mUITrueCell;
        
        private WinCheckBox mUIItemCheckBox;
        
        private WinCell mUIItem0Cell;
        
        private WinEdit mUI_grdJobOrderScheduleEdit;
        
        private WinCell mUIItem0Cell1;
        
        private WinEdit mUI_grdJobOrderScheduleEdit1;
        
        private WinCell mUIItem0Cell2;
        
        private WinEdit mUI_grdJobOrderScheduleEdit2;
        
        private WinCell mUIItem0Cell3;
        
        private WinEdit mUI_grdJobOrderScheduleEdit3;
        
        private WinCell mUIItem0Cell4;
        
        private WinEdit mUI_grdJobOrderScheduleEdit4;
        
        private WinCell mUIItemCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            #endregion
        }
        
        #region Properties
        public WinClient UIDesktopClient
        {
            get
            {
                if ((this.mUIDesktopClient == null))
                {
                    this.mUIDesktopClient = new WinClient(this);
                }
                return this.mUIDesktopClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIDesktopClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIEstimatedHoursWindow : WinWindow
    {
        
        public UIEstimatedHoursWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Estimated Hours";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Estimated Hours");
            #endregion
        }
        
        #region Properties
        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UI_mskEstimatedHrsWindow UI_mskEstimatedHrsWindow
        {
            get
            {
                if ((this.mUI_mskEstimatedHrsWindow == null))
                {
                    this.mUI_mskEstimatedHrsWindow = new UI_mskEstimatedHrsWindow(this);
                }
                return this.mUI_mskEstimatedHrsWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow2 mUIItemWindow;
        
        private UI_mskEstimatedHrsWindow mUI_mskEstimatedHrsWindow;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Estimated Hours");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Estimated Hours");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UI_mskEstimatedHrsWindow : WinWindow
    {
        
        public UI_mskEstimatedHrsWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_mskEstimatedHrs";
            this.WindowTitles.Add("Estimated Hours");
            #endregion
        }
        
        #region Properties
        public UI_mskEstimatedHrsEdit UI_mskEstimatedHrsEdit
        {
            get
            {
                if ((this.mUI_mskEstimatedHrsEdit == null))
                {
                    this.mUI_mskEstimatedHrsEdit = new UI_mskEstimatedHrsEdit(this);
                }
                return this.mUI_mskEstimatedHrsEdit;
            }
        }
        
        public WinEdit UI_mskEstimatedHrsEdit1
        {
            get
            {
                if ((this.mUI_mskEstimatedHrsEdit1 == null))
                {
                    this.mUI_mskEstimatedHrsEdit1 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_mskEstimatedHrsEdit1.SearchProperties[WinEdit.PropertyNames.Name] = "4";
                    this.mUI_mskEstimatedHrsEdit1.WindowTitles.Add("Estimated Hours");
                    #endregion
                }
                return this.mUI_mskEstimatedHrsEdit1;
            }
        }
        #endregion
        
        #region Fields
        private UI_mskEstimatedHrsEdit mUI_mskEstimatedHrsEdit;
        
        private WinEdit mUI_mskEstimatedHrsEdit1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UI_mskEstimatedHrsEdit : WinEdit
    {
        
        public UI_mskEstimatedHrsEdit(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinEdit.PropertyNames.Name] = "Text area";
            this.WindowTitles.Add("Estimated Hours");
            #endregion
        }
        
        #region Properties
        public WinEdit UI_mskEstimatedHrsEdit1
        {
            get
            {
                if ((this.mUI_mskEstimatedHrsEdit1 == null))
                {
                    this.mUI_mskEstimatedHrsEdit1 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_mskEstimatedHrsEdit1.SearchProperties[WinEdit.PropertyNames.Name] = "A single text character";
                    this.mUI_mskEstimatedHrsEdit1.SearchProperties[WinEdit.PropertyNames.Instance] = "2";
                    this.mUI_mskEstimatedHrsEdit1.WindowTitles.Add("Estimated Hours");
                    #endregion
                }
                return this.mUI_mskEstimatedHrsEdit1;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUI_mskEstimatedHrsEdit1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnOk";
            this.WindowTitles.Add("Estimated Hours");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Estimated Hours");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
